const USER_NAME_OR_PASSWORD_ERROR = '用户名或密码错误，请重新登录';
const TOKEN_AUTHENTICATION_FAILED = 'token验证失败，请重新登录';
const USER_NAME_IS_NOT_EXIST ='用户名不存在';
const CHAPTER_NAME_DOES_NOT_SAME ='章节名称不能重复';
module.exports = {
  USER_NAME_OR_PASSWORD_ERROR,
  TOKEN_AUTHENTICATION_FAILED,
  USER_NAME_IS_NOT_EXIST,
  CHAPTER_NAME_DOES_NOT_SAME
}